ZG: ZGPeerSession Class Reference
ZGPeerSession Class Reference abstract
This is the class that a user program would typically subclass from and add to a ReflectServer in order to participate in a ZG system.
#include <ZGPeerSession.h>
Public Member Functions
ZGPeerSession (const ZGPeerSettings &peerSettings)
Constructor.
virtual status_t AttachedToServer ()
Called when this session object is attached to the ReflectServer object.
virtual void AboutToDetachFromServer ()
Called just before this session object is detached from the ReflectServer object.
virtual void EndSession ()
Call this to request the termination of this session and its detachment from the ReflectServer.
virtual uint64 GetPulseTime (const PulseArgs &args)
Returns the time (in microseconds, using the timebase of GetRunTime64()) when Pulse() should next be called.
virtual void Pulse (const PulseArgs &args)
Called at (approximately) the time specified by GetPulseTime().
virtual bool IsReadyForTextCommands () const
Default implementation returns true iff we are currently fully attached to the ZG system.
virtual bool TextCommandReceived (const String &text)
Default implementation handles some standard ZG commands such as "print peers" or "print sessions".
bool IAmTheSeniorPeer () const
Returns true iff this peer is currently considered to be the senior peer of the system.
const ZGPeerSettings & GetPeerSettings () const
Returns the ZGPeerSettings object, as passed to our constructor.
virtual void NetworkInterfacesChanged (const Hashtable< String, Void > &optInterfaceNames)
Called when the set of available network interfaces on this computer has changed.
virtual void ComputerIsAboutToSleep ()
Called just before this computer goes to sleep (e.g.
virtual void ComputerJustWokeUp ()
Called just after this computer woke up from sleep (e.g.
bool IAmFullyAttached () const
Returns true iff this peer is fully attached to the system (i.e.
virtual void LocalSeniorPeerStatusChanged ()
Called whenever this peer has gained or lost senior-peer status (current status is indicated by the return value of IAmTheSeniorPeer())
const ZGPeerID & GetLocalPeerID () const
Returns the ZGPeerID being used by this local peer.
const ZGPeerID & GetSeniorPeerID () const
Returns the ZGPeerID of the senior peer of this system, or an invalid ZGPeerID if there currently is no senior peer (that we know of).
virtual uint64 GetNetworkTime64 () const
Returns the current time according to the network-time-clock, in microseconds.
virtual uint64 GetRunTime64ForNetworkTime64 (uint64 networkTime64TimeStamp) const
Given a network-time-clock-value (i.e.
virtual uint64 GetNetworkTime64ForRunTime64 (uint64 runTime64TimeStamp) const
Given a local-time-clock-value (i.e.
virtual int64 GetToNetworkTimeOffset () const
Returns the number of microseconds that should be added to a GetRunTime64() value to turn it into a GetNetworkTime64() value, or subtracted to do the inverse operation.
const Hashtable< ZGPeerID,
ConstMessageRef > & GetOnlinePeers () const
Returns a reference to a read-only table of the peers that are currently online in the system.
bool IsPeerOnline (const ZGPeerID &peerID) const
Returns true iff if the specified peer is currently online.
uint64 GetEstimatedLatencyToPeer (const ZGPeerID &peerID) const
Gets our current estimate of the one-way network latency between us and the specified peer.
Protected Member Functions
status_t RequestResetDatabaseStateToDefault (uint32 whichDatabase)
Call this if you want to request that the specified database be reset back to its well-known default state.
status_t RequestReplaceDatabaseState (uint32 whichDatabase, const MessageRef &newDatabaseStateMsg)
Call this if you want to request that the specified database be completely replaced with a new state that is specified by the passed-in Message.
status_t RequestUpdateDatabaseState (uint32 whichDatabase, const MessageRef &databaseUpdateMsg)
Call this if you want to request that the specified database be incrementally updated to a new state via a specified passed-in Message.
virtual void MessageReceivedFromGateway (const MessageRef &msg, void *userData)
Implemented as a no-op, since by default this session doesn't have a gateway.
virtual void ResetLocalDatabaseToDefault (uint32 whichDatabase, uint32 &dbChecksum)=0
Must be implemented to reset local state of the specified database to its well-known default state.
virtual ConstMessageRef SeniorUpdateLocalDatabase (uint32 whichDatabase, uint32 &dbChecksum, const ConstMessageRef &seniorDoMsg)=0
This method will only be called on the senior peer.
virtual status_t JuniorUpdateLocalDatabase (uint32 whichDatabase, uint32 &dbChecksum, const ConstMessageRef &juniorDoMsg)=0
This method will only be called on junior peers.
virtual MessageRef SaveLocalDatabaseToMessage (uint32 whichDatabase) const =0
This method should be implemented to save the state of the specified local database into a Message.
virtual status_t SetLocalDatabaseFromMessage (uint32 whichDatabase, uint32 &dbChecksum, const ConstMessageRef &newDBStateMsg)=0
This method should be implemented to replace the current state of the specified local database with the new state represented by the passed-in Message.
virtual uint32 CalculateLocalDatabaseChecksum (uint32 whichDatabase) const =0
This method is used for sanity-checking.
virtual String GetLocalDatabaseContentsAsString (uint32 whichDatabase) const
This method may be implemented to return a human-readable representation of the specified database's current contents as a String.
virtual void PeerHasComeOnline (const ZGPeerID &peerID, const ConstMessageRef &peerInfo)
Called when a new peer has joined our group.
virtual void PeerHasGoneOffline (const ZGPeerID &peerID, const ConstMessageRef &peerInfo)
Called when a peer has left our group.
virtual void SeniorPeerChanged (const ZGPeerID &oldSeniorPeerID, const ZGPeerID &newSeniorPeerID)
Called when the senior peer of our peer group has changed.
status_t SendMulticastUserMessageToAllPeers (const MessageRef &msg)
Tries to send the given Message to all peers (except this one) via UDP multicast.
status_t SendUnicastUserMessageToAllPeers (const MessageRef &msg)
Tries to send the given Message to all peers (except this one) via multiple instances of TCP unicast.
status_t SendUnicastUserMessageToPeer (const ZGPeerID &destinationPeerID, const MessageRef &msg)
Tries to send the given Message to a specific peers via TCP unicast.
void PrintDatabaseStateInfo (int32 whichDatabase=-1) const
Prints various database-state information to stdout.
void PrintDatabaseUpdateLog (int32 whichDatabase=-1) const
Prints the database update-log(s) to stdout.
bool ParseGenericTextCommand (const String &cmd)
Tries to handle any text commands that can be handled generically; that is, any commands that can be handled without knowing anything about this particular application.
Detailed Description
This is the class that a user program would typically subclass from and add to a ReflectServer in order to participate in a ZG system.
Definition at line 28 of file ZGPeerSession.h.
Constructor & Destructor Documentation
ZGPeerSession (const ZGPeerSettings & peerSettings)
Constructor.
Parameters
peerSettings the ZGPeerSettings that this system is to use.
Member Function Documentation
virtual void AboutToDetachFromServer () virtual
Called just before this session object is detached from the ReflectServer object.
virtual status_t AttachedToServer () virtual
Called when this session object is attached to the ReflectServer object.
Returns
true iff the attaching process went okay, or false if there was an error and the attachment should be aborted.
Reimplemented in ZGDatabasePeerSession.
virtual uint32 CalculateLocalDatabaseChecksum (uint32 whichDatabase) const protected pure virtual
This method is used for sanity-checking.
It should be implemented to scan the specified local database and return a checksum representing all of the data in the database. This checksum should match the checksums returned/updated by the SeniorUpdateLocalDatabase() and JuniorUpdateLocalDatabase() functions for the same database state.
Implemented in ZGDatabasePeerSession.
virtual void ComputerIsAboutToSleep () inline virtual
Called just before this computer goes to sleep (e.g.
due to closing a laptop lid)
Definition at line 83 of file ZGPeerSession.h.
virtual void ComputerJustWokeUp () inline virtual
Called just after this computer woke up from sleep (e.g.
due to opening a laptop lid)
Definition at line 86 of file ZGPeerSession.h.
virtual void EndSession () virtual
Call this to request the termination of this session and its detachment from the ReflectServer.
Overridden to do some thread-shutdown work to avoid race conditions.
uint64 GetEstimatedLatencyToPeer (const ZGPeerID & peerID) const
Gets our current estimate of the one-way network latency between us and the specified peer.
Parameters
peerID The peer ID to get the latency of
Returns
The estimated latency, in microseconds, or MUSCLE_TIME_NEVER if the latency is unknown.
virtual String GetLocalDatabaseContentsAsString (uint32 whichDatabase) const protected virtual
This method may be implemented to return a human-readable representation of the specified database's current contents as a String.
This string will be printed to stdout after a checksum error has occurred, to make it easier to debug the update logic (i.e. by comparing the database state before and after the checksum-mismatched database was replaced, to see what is different). The default implementation of this method just returns "(GetLocalDatabaseContentsAsString unimplemented)".
Parameters
whichDatabase The index of the database to return a string for.
Reimplemented in ZGDatabasePeerSession.
const ZGPeerID& GetLocalPeerID () const inline
Returns the ZGPeerID being used by this local peer.
Returned value is not valid until after ZGPeerSession::AttachedToServer() returns B_NO_ERROR.
Definition at line 95 of file ZGPeerSession.h.
virtual uint64 GetNetworkTime64 () const inline virtual
Returns the current time according to the network-time-clock, in microseconds.
The intent of this clock is to be the same on all peers in the system. However, this means that it may occasionally change (break monotonicity) in order to synchronize with the other peers in the system. Note that this function will return 0 if we aren't currently fully attached to the system, since before then we don't know the network time.
Implements INetworkTimeProvider.
Definition at line 105 of file ZGPeerSession.h.
References ZGPeerSession::GetNetworkTime64ForRunTime64().
virtual uint64 GetNetworkTime64ForRunTime64 (uint64 runTime64TimeStamp) const inline virtual
Given a local-time-clock-value (i.e.
one using the same time-base as returned by GetRunTime64()), returns the approximately equivalent network-time-value (i.e. one using the same time-base as returned by GetNetworkTime64())
Implements INetworkTimeProvider.
Definition at line 115 of file ZGPeerSession.h.
References ZGPeerSession::GetToNetworkTimeOffset().
Referenced by ZGPeerSession::GetNetworkTime64().
const Hashtable<ZGPeerID, ConstMessageRef>& GetOnlinePeers () const inline
Returns a reference to a read-only table of the peers that are currently online in the system.
The keys in the table are the peer's IDs, and the values are the peers' attributes (may be NULL if they didn't advertise any) The ordering of the entries in the table is not significant (in particular, it doesn't reflect the ordering of the peers' seniority, at least not for now).
Definition at line 126 of file ZGPeerSession.h.
const ZGPeerSettings& GetPeerSettings () const inline
Returns the ZGPeerSettings object, as passed to our constructor.
Definition at line 73 of file ZGPeerSession.h.
virtual uint64 GetPulseTime (const PulseArgs & args) virtual
Returns the time (in microseconds, using the timebase of GetRunTime64()) when Pulse() should next be called.
Parameters
args Context information for this call (including the current time and the time at which Pulse() was supposed to be called at)
Returns
a new time in microseconds, or MUSCLE_TIME_NEVER if we don't need Pulse() to be called.
Reimplemented in ChoirSession.
virtual uint64 GetRunTime64ForNetworkTime64 (uint64 networkTime64TimeStamp) const inline virtual
Given a network-time-clock-value (i.e.
one using the same time-base as returned by GetNetworkTime64()), returns the approximately-equivalent local-time-clock-value (i.e. one using the same time-base as returned by GetRunTime64())
Implements INetworkTimeProvider.
Definition at line 110 of file ZGPeerSession.h.
References ZGPeerSession::GetToNetworkTimeOffset().
const ZGPeerID& GetSeniorPeerID () const inline
Returns the ZGPeerID of the senior peer of this system, or an invalid ZGPeerID if there currently is no senior peer (that we know of).
Definition at line 98 of file ZGPeerSession.h.
virtual int64 GetToNetworkTimeOffset () const virtual
Returns the number of microseconds that should be added to a GetRunTime64() value to turn it into a GetNetworkTime64() value, or subtracted to do the inverse operation.
Note that this value will vary from one moment to the next!
Implements INetworkTimeProvider.
Referenced by ZGPeerSession::GetNetworkTime64ForRunTime64(), and ZGPeerSession::GetRunTime64ForNetworkTime64().
bool IAmFullyAttached () const inline
Returns true iff this peer is fully attached to the system (i.e.
has completed enumeration of which other peers are online, etc)
Definition at line 89 of file ZGPeerSession.h.
bool IAmTheSeniorPeer () const
Returns true iff this peer is currently considered to be the senior peer of the system.
bool IsPeerOnline (const ZGPeerID & peerID) const
Returns true iff if the specified peer is currently online.
Parameters
peerID The peer ID to check on.
virtual bool IsReadyForTextCommands () const inline virtual
Default implementation returns true iff we are currently fully attached to the ZG system.
Implements ITextCommandReceiver.
Definition at line 61 of file ZGPeerSession.h.
virtual status_t JuniorUpdateLocalDatabase (uint32 whichDatabase, uint32 & dbChecksum, const ConstMessageRef & juniorDoMsg) protected pure virtual
This method will only be called on junior peers.
It must be implemented to update the junior peer's local database according to the instructions contained in (juniorDoMsg).
Parameters
whichDatabase The index of the database to update (e.g. 0 for the first database, 1 for the second, and so on)
dbChecksum Passed in as the database's current checksum value. On return, this should be set to the database's new (post-update) checksum value.
juniorDoMsg Reference to a Message instructing the junior peer how his lcoal database should be updated. (The contents and semantics of this Message will be determined by logic in the subclass of this class; they are not specified by the ZGPeerSession class itself)
Returns
on success, returns B_NO_ERROR. On failure (or refusal-to-update), returns B_ERROR.
Implemented in ZGDatabasePeerSession.
virtual void LocalSeniorPeerStatusChanged () virtual
Called whenever this peer has gained or lost senior-peer status (current status is indicated by the return value of IAmTheSeniorPeer())
virtual void MessageReceivedFromGateway (const MessageRef & msg, void * userData) protected virtual
Implemented as a no-op, since by default this session doesn't have a gateway.
virtual void NetworkInterfacesChanged (const Hashtable< String, Void > & optInterfaceNames) inline virtual
Called when the set of available network interfaces on this computer has changed.
Default implementation is a no-op.
Parameters
optInterfaceNames An optional list of network-interface names (e.g. "eth0", "eth1") that are known to have changed. If empty, then you should assume that any or all network interfaces have changed.
Definition at line 80 of file ZGPeerSession.h.
bool ParseGenericTextCommand (const String & cmd) protected inherited
Tries to handle any text commands that can be handled generically; that is, any commands that can be handled without knowing anything about this particular application.
This logic is broken out into a separate function so that it can be called by the stdin-text handlers of various daemons.
Parameters
cmd the command text to parse
Returns
true if the command was handled, false if it wasn't.
virtual void PeerHasComeOnline (const ZGPeerID & peerID, const ConstMessageRef & peerInfo) protected virtual
Called when a new peer has joined our group.
Parameters
peerID The unique ID of the peer who is now online. (Note that this ID may be our own ID!)
peerInfo An optional Message containing some additional information about that peer, if that peer specified any additional information in his ZGPeerSettings object. May be a NULL reference otherwise.
Reimplemented in ChoirSession.
virtual void PeerHasGoneOffline (const ZGPeerID & peerID, const ConstMessageRef & peerInfo) protected virtual
Called when a peer has left our group.
Parameters
peerID The unique ID of the peer who is now offline.
peerInfo An optional Message containing some additional information about that peer, if that peer specified any additional information in his ZGPeerSettings object. May be a NULL reference otherwise.
Reimplemented in ChoirSession.
void PrintDatabaseStateInfo (int32 whichDatabase = -1) const protected
Prints various database-state information to stdout.
Useful for debugging purposes.
Parameters
whichDatabase Index of the database to print out state for, or leave set to -1 to print out info about all databases.
void PrintDatabaseUpdateLog (int32 whichDatabase = -1) const protected
Prints the database update-log(s) to stdout.
Useful for debugging purposes.
Parameters
whichDatabase Index of the database to print out the update-log for, or leave set to -1 to print out the update-logs of all databases.
virtual void Pulse (const PulseArgs & args) virtual
Called at (approximately) the time specified by GetPulseTime().
Parameters
args Context information for this call (including the current time and the time at which this method was supposed to be called at)
Reimplemented in ChoirSession.
status_t RequestReplaceDatabaseState (uint32 whichDatabase, const MessageRef & newDatabaseStateMsg) protected
Call this if you want to request that the specified database be completely replaced with a new state that is specified by the passed-in Message.
The new database state will be created by calling SetLocalDatabaseFromMessage(newDatabaseStateMsg) on the senior peer. Note that this method only sends the request; the actual database-replace will happen (if it happens) some time after this method returns.
Parameters
whichDatabase the index of the database whose state should be replaced.
newDatabaseStateMsg a Message containing instructions/data that SetLocalDatabaseFromMessage() can use later on to create a new database state.
Returns
B_NO_ERROR if the the replace-request was successfully sent to the senior peer, or B_ERROR if the request could not be sent.
status_t RequestResetDatabaseStateToDefault (uint32 whichDatabase) protected
Call this if you want to request that the specified database be reset back to its well-known default state.
The well-known default state is defined by the implementation of the subclass's ResetLocalDatabaseToDefault() method. Note that this method only sends the request; the actual reset will happen (if it happens) some time after this method returns.
Parameters
whichDatabase the index of the database that should be reset
Returns
B_NO_ERROR if the the reset-request was successfully sent to the senior peer, or B_ERROR if the request could not be sent.
status_t RequestUpdateDatabaseState (uint32 whichDatabase, const MessageRef & databaseUpdateMsg) protected
Call this if you want to request that the specified database be incrementally updated to a new state via a specified passed-in Message.
The new database state will be created by calling SeniorUpdateLocalDatabase(databaseUpdateMsg) on the senior peer, and then the Message returned by that method call will be used to update the local database of all of the other peers. Note that this method only sends the request; the actual database-update will happen (if it happens) some time after this method returns.
Parameters
whichDatabase the index of the database whose state should be updated.
databaseUpdateMsg a Message containing instructions/data that SeniorUpdateLocalDatabase() can use later on to transition the database to a new database state.
Returns
B_NO_ERROR if the the update-request was successfully sent to the senior peer, or B_ERROR if the request could not be sent.
virtual void ResetLocalDatabaseToDefault (uint32 whichDatabase, uint32 & dbChecksum) protected pure virtual
Must be implemented to reset local state of the specified database to its well-known default state.
Parameters
whichDatabase The index of the database to reset (e.g. 0 for the first database, 1 for the second, and so on)
dbChecksum Passed in as the database's current checksum value. On return, this should be set to the database's new checksum value.
Implemented in ZGDatabasePeerSession.
virtual MessageRef SaveLocalDatabaseToMessage (uint32 whichDatabase) const protected pure virtual
This method should be implemented to save the state of the specified local database into a Message.
Parameters
whichDatabase The index of the database to save (e.g. 0 for the first database, 1 for the second, and so on)
Returns
a MessageRef containing the full current state of the local database, or a NULL MessageRef on failure.
Implemented in ZGDatabasePeerSession.
status_t SendMulticastUserMessageToAllPeers (const MessageRef & msg) protected
Tries to send the given Message to all peers (except this one) via UDP multicast.
The PacketTunnelIOGateway mechanism is used so that large Messages can be transmitted as well as small ones. Delivery is not guaranteed, however.
Parameters
msg The Message object to send. MessageReceivedFromPeer() will be called on each peer when the Message arrives there.
Returns
B_NO_ERROR if the Message was successfully enqueued to be multicasted out, of B_ERROR otherwise.
status_t SendUnicastUserMessageToAllPeers (const MessageRef & msg) protected
Tries to send the given Message to all peers (except this one) via multiple instances of TCP unicast.
Parameters
msg The Message object to send. MessageReceivedFromPeer() will be called on each peer when the Message arrives there.
Returns
B_NO_ERROR if the Message was successfully enqueued to be multicasted out, of B_ERROR otherwise.
status_t SendUnicastUserMessageToPeer (const ZGPeerID & destinationPeerID, const MessageRef & msg) protected
Tries to send the given Message to a specific peers via TCP unicast.
Parameters
destinationPeerID The ZGPeerID of the peer we want this Message to be sent to.
msg The Message object to send. MessageReceivedFromPeer() will be called on the peer when the Message arrives there.
Returns
B_NO_ERROR if the Message was successfully enqueued to be unicasted out, of B_ERROR otherwise.
virtual void SeniorPeerChanged (const ZGPeerID & oldSeniorPeerID, const ZGPeerID & newSeniorPeerID) protected virtual
Called when the senior peer of our peer group has changed.
Parameters
oldSeniorPeerID The unique ID of the peer who was the senior peer but no longer is. (May be a zero/invalid if there wasn't any senior peer before)
newSeniorPeerID The unique ID of the peer who is now the senior peer. (May be a zero/invalid if there is no senior peer anymore)
Reimplemented in ChoirSession.
virtual ConstMessageRef SeniorUpdateLocalDatabase (uint32 whichDatabase, uint32 & dbChecksum, const ConstMessageRef & seniorDoMsg) protected pure virtual
This method will only be called on the senior peer.
It must be implemented to update the senior peer's local database and return a MessageRef that the system can later use to update same database on the various junior peers in the same way later on.
Parameters
whichDatabase The index of the database to update (e.g. 0 for the first database, 1 for the second, and so on)
dbChecksum Passed in as the database's current checksum value. On return, this should be set to the database's new (post-update) checksum value.
seniorDoMsg Reference to a Message instructing the senior peer how his local database should be updated. (The contents and semantics of this Message will be determined by logic in the subclass of this class; they are not specified by the ZGPeerSession class itself)
Returns
on success, this method should return a MessageRef that can be sent on to the junior peers to tell them how to update their local database so that their local database ends up in the same post-change state that our local database is currently in. Returning (seniorDoMsg) is acceptable if that is a Message that will cause the junior peers to do the right thing. On failure (or refusal-to-handle-the-update), a NULL MessageRef() should be returned.
Implemented in ZGDatabasePeerSession.
virtual status_t SetLocalDatabaseFromMessage (uint32 whichDatabase, uint32 & dbChecksum, const ConstMessageRef & newDBStateMsg) protected pure virtual
This method should be implemented to replace the current state of the specified local database with the new state represented by the passed-in Message.
Parameters
whichDatabase The index of the database to replace (e.g. 0 for the first database, 1 for the second, and so on)
dbChecksum Passed in as the database's current checksum value. On return, this should be set to the database's new (post-update) checksum value.
newDBStateMsg A Message holding the contents of the new database we want to replace the current database with.
Returns
B_NO_ERROR on success, or B_ERROR on failure.
Implemented in ZGDatabasePeerSession.
virtual bool TextCommandReceived (const String & text) virtual
Default implementation handles some standard ZG commands such as "print peers" or "print sessions".
Parameters
text A text string was received via our stdin stream.
Returns
true if the command was recognized and handled, or false otherwise.
Implements ITextCommandReceiver.
The documentation for this class was generated from the following file:
ZGPeerSession.h